### ISSUE TITLE
bug reports

### ISSUE THREAD

**Issue by AmirulAndalib** [FlawCra/ReactSelfbot#6]
`[05:17:45] Command Used | help
something went wrong, here is some info:
Traceback (most recent call last):
  File "React.py", line 125543, in on_command
    requests.post(json.load(open('config.json', encoding='utf-8'))['command_usage_webhook'], data=payload.encode(), headers={'Content-Type': 'application/json', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11'})
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'OPTIONAL': No schema supplied. Perhaps you meant http://OPTIONAL?
something went wrong, here is some info:
Traceback (most recent call last):
  File "React.py", line 6934, in on_message
    if data[msg.content]:
KeyError: ''
Task exception was never retrieved
future: <Task finished name='Task-107' coro=<Message.delete.<locals>.delete() done, defined at /opt/virtualenvs/python3/lib/python3.8/site-packages/discord/message.py:1014> exception=TypeError("'<=' not supported between instances of 'str' and 'int'")>
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/message.py", line 1015, in delete
    await asyncio.sleep(delay)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 643, in sleep
    if delay <= 0:
TypeError: '<=' not supported between instances of 'str' and 'int'`

`[05:16:36] Command Used | typing
something went wrong, here is some info:
Traceback (most recent call last):
  File "React.py", line 125543, in on_command
    requests.post(json.load(open('config.json', encoding='utf-8'))['command_usage_webhook'], data=payload.encode(), headers={'Content-Type': 'application/json', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11'})
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'OPTIONAL': No schema supplied. Perhaps you meant http://OPTIONAL?
something went wrong, here is some info:
Traceback (most recent call last):
  File "React.py", line 6934, in on_message
    if data[msg.content]:
KeyError: '.typing 130921039012930912309120392103'
[05:16:52] Command Used | typing
something went wrong, here is some info:
Traceback (most recent call last):
  File "React.py", line 125543, in on_command
    requests.post(json.load(open('config.json', encoding='utf-8'))['command_usage_webhook'], data=payload.encode(), headers={'Content-Type': 'application/json', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11'})
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'OPTIONAL': No schema supplied. Perhaps you meant http://OPTIONAL?
172.18.0.1 - - [10/Oct/2021 05:17:01] "GET / HTTP/1.1" 200 -
something went wrong, here is some info:
Traceback (most recent call last):
  File "React.py", line 6934, in on_message
    if data[msg.content]:
KeyError: '.help'`

`something went wrong, here is some info:
Traceback (most recent call last):
  File "React.py", line 126997, in load_command_descriptions
    cmd.update(description=command_description, usage=command_usage)
AttributeError: 'NoneType' object has no attribute 'update'
something went wrong, here is some info:
Traceback (most recent call last):
  File "React.py", line 126997, in load_command_descriptions
    cmd.update(description=command_description, usage=command_usage)
AttributeError: 'NoneType' object has no attribute 'update'
something went wrong, here is some info:
Traceback (most recent call last):
  File "React.py", line 5867, in on_ready
    playsound.playsound(os.path.dirname(__file__)+"\\Sound\\connected.mp3")
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/playsound.py", line 254, in <lambda>
    playsound = lambda sound, block = True: _playsoundAnotherPython('/usr/bin/python3', sound, block, macOS = False)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/playsound.py", line 223, in _playsoundAnotherPython
    raise PlaysoundException('Cannot find a sound with filename: ' + sound)
playsound.PlaysoundException: Cannot find a sound with filename: \Sound\connected.mp3`

## i am running on repl it

**Comment by 404Ako** [comment]
It's because you have ran it in replit try deleting the sounds folder

**Comment by AmirulAndalib** [comment]
no everythings is Present

**Comment by ForyxCraft** [comment]
@404Ako I think that's not possible because React downloads all sound files during startup

**Comment by AmirulAndalib** [comment]
@ForyxCraft i want to disable all webhooks also  my RPC and also the  default provided rpc doesnt show up on my account only twitch stream is working here is my [config.json](https://nekobin.com/jabuhoyafe) file  please check
